version: "3.8"
services:
    server:
        build: ./server
        ports: 
            - 5050:5000
        command: npm run dev
        restart: always
        volumes: 
            - ./server:/app/server
            - '/app/server/node_modules'
    mongodb:
        image: mongo
        volumes: 
            - ./data:/data/db
    client:
        build:
            context: ./client
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./client:/app/client
            - '/app/client/node_modules'
        ports:
            - 8080:3000
        environment:
            - CHOKIDAR_USEPOLLING=true